name: Demo - Store Artifact

on:
  workflow_dispatch:

jobs:
  build-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a file to store
        run: |
          mkdir output
          echo "🎉 This is a test artifact!" > output/hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: demo-artifact
          path: output/hello.txt
