name: Demo - Store Artifact

on:
  workflow_dispatch:

jobs:
  build-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: |
          echo "Files in the repo:"
          ls -la  # This will list the files in the repo
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: demo-artifact
          path: output/hello.txt
